CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START 1;

CREATE TABLE IF NOT EXISTS TROPOGO.JOB_HISTORY
(
    ID                  INTEGER         NOT NULL PRIMARY KEY,
    COMPANY             VARCHAR(100)    NOT NULL,
    TITLE               VARCHAR(100)    NOT NULL,
    DESCRIPTION         VARCHAR(500)    NOT NULL,
    LOCATION            VARCHAR(100)    NOT NULL,
    EXPERIENCE_RANGE    VARCHAR(100)    NOT NULL,
    SALARY_RANGE        VARCHAR(100)    NOT NULL,
    POSTED_BY           VARCHAR(100)    NOT NULL,
    POSTED_DATE         DATE            NOT NULL
);